name: CI
on: push
jobs:
  marketplace_action:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      
      - name: setup-uv
        uses: astral-sh/setup-uv@v6
      
      - name: uv-lock
        run: uv sync --frozen --all-groups