name: CI
on: push
jobs:
  marketplace_action:
    runs-on: ubuntu-latest
    steps: 
      - name: marketplace_action
        uses: actions/checkout@v4
        uses: astral-sh/setup-uv@v6
        run: uv sync --frozen --all-groups